# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

RC=rustc
CU=clang
CC=cl.exe
MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\rc.exe
CXX=cl.exe
AS=ml64.exe

SH=link.exe -dll
RCSH=rustc
LD=link.exe
RCLD=rustc
AR=link.exe -lib
RCAR=rustc

main_CXXFLAGS=-FS -Zi -Fdbuild\windows\x64\release\compile.main.pdb -Od -Iinclude -Iinclude\glad -I..\..\libs\glfw-3.3\include -I..\..\libs\glm /EHsc /Zi /FS -nologo
main_CCFLAGS=-FS -Zi -Fdbuild\windows\x64\release\compile.main.pdb -Od -Iinclude -Iinclude\glad -I..\..\libs\glfw-3.3\include -I..\..\libs\glm /EHsc /Zi /FS -nologo
main_LDFLAGS=-libpath:..\..\libs\glfw-3.3\lib -debug -pdb:build\windows\x64\release\main.pdb glfw3dll.lib user32.lib opengl32.lib gdi32.lib shell32.lib -nologo -dynamicbase -nxcompat -machine:x64

default:  main

all:  main

.PHONY: default all  main

main: build\windows\x64\release\main.exe
build\windows\x64\release\main.exe: build\.objs\main\windows\x64\release\src\ResourceManager.cpp.obj build\.objs\main\windows\x64\release\src\imgui_stdlib.cpp.obj build\.objs\main\windows\x64\release\src\Shader.cpp.obj build\.objs\main\windows\x64\release\src\imgui_impl_glfw.cpp.obj build\.objs\main\windows\x64\release\src\buffers\VertexArray.cpp.obj build\.objs\main\windows\x64\release\src\SimpleRenderer.cpp.obj build\.objs\main\windows\x64\release\src\buffers\IndexBuffer.cpp.obj build\.objs\main\windows\x64\release\src\buffers\FrameBuffer.cpp.obj build\.objs\main\windows\x64\release\src\GpuParticle.cpp.obj build\.objs\main\windows\x64\release\src\imgui_impl_opengl3.cpp.obj build\.objs\main\windows\x64\release\src\imgui_demo.cpp.obj build\.objs\main\windows\x64\release\src\BatchRenderer.cpp.obj build\.objs\main\windows\x64\release\src\Texture.cpp.obj build\.objs\main\windows\x64\release\src\StaticSprite.cpp.obj build\.objs\main\windows\x64\release\src\imgui_widgets.cpp.obj build\.objs\main\windows\x64\release\src\Sprite.cpp.obj build\.objs\main\windows\x64\release\src\imgui.cpp.obj build\.objs\main\windows\x64\release\.\main.cpp.obj build\.objs\main\windows\x64\release\src\imgui_draw.cpp.obj build\.objs\main\windows\x64\release\src\buffers\Buffer.cpp.obj build\.objs\main\windows\x64\release\src\Renderer.cpp.obj build\.objs\main\windows\x64\release\src\AnimatedSprite.cpp.obj build\.objs\main\windows\x64\release\src\Camera.cpp.obj build\.objs\main\windows\x64\release\src\Window.cpp.obj build\.objs\main\windows\x64\release\src\Game.cpp.obj build\.objs\main\windows\x64\release\src\glad.c.obj
	@echo linking.release main.exe
	-@mkdir build\windows\x64\release > NUL 2>&1
	@$(LD) @C:\Users\jatin\AppData\Local\Temp\.xmake\200927\_D8F63C46C97048128D66B5F01D5470AA.args.txt > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\ResourceManager.cpp.obj: src\ResourceManager.cpp
	@echo compiling.release src\ResourceManager.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\ResourceManager.cpp.obj src\ResourceManager.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\imgui_stdlib.cpp.obj: src\imgui_stdlib.cpp
	@echo compiling.release src\imgui_stdlib.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\imgui_stdlib.cpp.obj src\imgui_stdlib.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\Shader.cpp.obj: src\Shader.cpp
	@echo compiling.release src\Shader.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\Shader.cpp.obj src\Shader.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\imgui_impl_glfw.cpp.obj: src\imgui_impl_glfw.cpp
	@echo compiling.release src\imgui_impl_glfw.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\imgui_impl_glfw.cpp.obj src\imgui_impl_glfw.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\buffers\VertexArray.cpp.obj: src\buffers\VertexArray.cpp
	@echo compiling.release src\buffers\VertexArray.cpp
	-@mkdir build\.objs\main\windows\x64\release\src\buffers > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\buffers\VertexArray.cpp.obj src\buffers\VertexArray.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\SimpleRenderer.cpp.obj: src\SimpleRenderer.cpp
	@echo compiling.release src\SimpleRenderer.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\SimpleRenderer.cpp.obj src\SimpleRenderer.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\buffers\IndexBuffer.cpp.obj: src\buffers\IndexBuffer.cpp
	@echo compiling.release src\buffers\IndexBuffer.cpp
	-@mkdir build\.objs\main\windows\x64\release\src\buffers > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\buffers\IndexBuffer.cpp.obj src\buffers\IndexBuffer.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\buffers\FrameBuffer.cpp.obj: src\buffers\FrameBuffer.cpp
	@echo compiling.release src\buffers\FrameBuffer.cpp
	-@mkdir build\.objs\main\windows\x64\release\src\buffers > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\buffers\FrameBuffer.cpp.obj src\buffers\FrameBuffer.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\GpuParticle.cpp.obj: src\GpuParticle.cpp
	@echo compiling.release src\GpuParticle.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\GpuParticle.cpp.obj src\GpuParticle.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\imgui_impl_opengl3.cpp.obj: src\imgui_impl_opengl3.cpp
	@echo compiling.release src\imgui_impl_opengl3.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\imgui_impl_opengl3.cpp.obj src\imgui_impl_opengl3.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\imgui_demo.cpp.obj: src\imgui_demo.cpp
	@echo compiling.release src\imgui_demo.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\imgui_demo.cpp.obj src\imgui_demo.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\BatchRenderer.cpp.obj: src\BatchRenderer.cpp
	@echo compiling.release src\BatchRenderer.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\BatchRenderer.cpp.obj src\BatchRenderer.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\Texture.cpp.obj: src\Texture.cpp
	@echo compiling.release src\Texture.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\Texture.cpp.obj src\Texture.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\StaticSprite.cpp.obj: src\StaticSprite.cpp
	@echo compiling.release src\StaticSprite.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\StaticSprite.cpp.obj src\StaticSprite.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\imgui_widgets.cpp.obj: src\imgui_widgets.cpp
	@echo compiling.release src\imgui_widgets.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\imgui_widgets.cpp.obj src\imgui_widgets.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\Sprite.cpp.obj: src\Sprite.cpp
	@echo compiling.release src\Sprite.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\Sprite.cpp.obj src\Sprite.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\imgui.cpp.obj: src\imgui.cpp
	@echo compiling.release src\imgui.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\imgui.cpp.obj src\imgui.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\.\main.cpp.obj: main.cpp
	@echo compiling.release main.cpp
	-@mkdir build\.objs\main\windows\x64\release\. > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\.\main.cpp.obj main.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\imgui_draw.cpp.obj: src\imgui_draw.cpp
	@echo compiling.release src\imgui_draw.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\imgui_draw.cpp.obj src\imgui_draw.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\buffers\Buffer.cpp.obj: src\buffers\Buffer.cpp
	@echo compiling.release src\buffers\Buffer.cpp
	-@mkdir build\.objs\main\windows\x64\release\src\buffers > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\buffers\Buffer.cpp.obj src\buffers\Buffer.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\Renderer.cpp.obj: src\Renderer.cpp
	@echo compiling.release src\Renderer.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\Renderer.cpp.obj src\Renderer.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\AnimatedSprite.cpp.obj: src\AnimatedSprite.cpp
	@echo compiling.release src\AnimatedSprite.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\AnimatedSprite.cpp.obj src\AnimatedSprite.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\Camera.cpp.obj: src\Camera.cpp
	@echo compiling.release src\Camera.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\Camera.cpp.obj src\Camera.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\Window.cpp.obj: src\Window.cpp
	@echo compiling.release src\Window.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\Window.cpp.obj src\Window.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\Game.cpp.obj: src\Game.cpp
	@echo compiling.release src\Game.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CXX) -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\Game.cpp.obj src\Game.cpp > build/.build.log 2>&1

build\.objs\main\windows\x64\release\src\glad.c.obj: src\glad.c
	@echo compiling.release src\glad.c
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	@$(CC) -c $(main_CCFLAGS) -Fobuild\.objs\main\windows\x64\release\src\glad.c.obj src\glad.c > build/.build.log 2>&1

clean:  clean_main

clean_main: 
	@del /F /Q build\windows\x64\release\main.exe > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\ResourceManager.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\imgui_stdlib.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\Shader.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\imgui_impl_glfw.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\buffers\VertexArray.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\SimpleRenderer.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\buffers\IndexBuffer.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\buffers\FrameBuffer.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\GpuParticle.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\imgui_impl_opengl3.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\imgui_demo.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\BatchRenderer.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\Texture.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\StaticSprite.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\imgui_widgets.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\Sprite.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\imgui.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\.\main.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\imgui_draw.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\buffers\Buffer.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\Renderer.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\AnimatedSprite.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\Camera.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\Window.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\Game.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\glad.c.obj > NUL 2>&1

